// THIS FILE IS GENERATED - DO NOT MODIFY
/**
 *  Autogenerated by current cli tool
 */
export const BUILD_FRAMEWORK_CLI_NAME = 'taon';
/**
 *  This value can be change in taon.jsonc (appId)
 */
export const APP_ID = 'com.domain.example.ng2-logger';
/**
 *  Autogenerated by current cli tool
 */
export const BUILD_BASE_HREF = '';
/**
 *  This value can be change in taon.jsonc (overrideNpmName)
 */
export const PROJECT_NPM_NAME = 'ng2-logger';
/**
 *  Autogenerated by current cli tool. Use *taon release* to bump version.
 */
export const CURRENT_PACKAGE_VERSION = '19.0.38';
// THIS FILE IS GENERATED - DO NOT MODIFY
      